# Generated by Django 4.2.3 on 2023-07-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
