# Generated by Django 4.2.3 on 2023-07-19 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.producttype'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 14, 31, 59, 246550)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 14, 31, 59, 246550)),
        ),
    ]
